// Generated by https://pagedraw.io/pages/11753
import React from "react";
import "./about.css";

export default class About extends React.Component {
  render() {
    return (
      <div className="about-about-9">
        <div className="about-0">
          <div className="about-about-0">About</div>
        </div>
        <div className="about-1">
          <div className="about-hi_my_name_is_felipe_luj_n_im_a_geologist_working_really_hard_to_switch_carrer_into_software_development_and_hopefully_some_ai_in_the_future_im_a_self-taught_developer_bilingual_english_and_spanish_i_ve_mainly_focused_on_front-end_frameworks_such_as_angular_2">
            <div>
              {
                "Hi. My name is Felipe Luján. Im a Geologist working really hard to switch carrer into software development and hopefully some AI in the future. Im a self-taught developer, bilingual (English and Spanish). "
              }
            </div>
            <div>
              {
                "I’ve mainly focused on Front-end frameworks such as Angular 2+ and React-Redux, but also worked quite a bit with Express servers on Node.js. Experienced with Linux environments."
              }
            </div>
          </div>
        </div>
        <div className="about-2" />
      </div>
    );
  }
}
