// Generated by https://pagedraw.io/pages/11751
import React from "react";
import "./component_1.css";

function render() {
  return (
    <div className="component_1-component_1">
      <div className="component_1-0">
        <div className="component_1-map-0">
          <div className="component_1-0-0-0">
            <div className="component_1-0-0-0-0">
              <div className="component_1-0-0-0-0-0">
                <div className="component_1-0-0-0-0-0-0">
                  <div className="component_1-felipe_lujan-0">Felipe Lujan</div>
                  <div className="component_1-rectangle_2" />
                </div>
              </div>
            </div>
          </div>
          <div className="component_1-0-0-1">
            <div className="component_1-0-0-1-0">
              <div className="component_1-0-0-1-0-0">
                <div className="component_1-0-0-1-0-0-0">
                  <div className="component_1-web_developer-0">
                    Web Developer
                  </div>
                  <div className="component_1-rectangle_2_" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function(props) {
  return render.apply({ props: props });
}
