// Generated by https://pagedraw.io/pages/11812
import React from "react";
import "./corners.css";

export default class Corners extends React.Component {
  render() {
    return (
      <div className="corners-corners-0">
        <div className="corners-0">
          <div className="corners-0-0">
            <div className="corners-cards_image_top_avatar_left-0">
              <div className="corners-0-0-0-0">
                <div className="corners-rectangle-0000">
                  <div className="corners-0-0-0-0-0-0">
                    <div className="corners-_base_surface_shape_atoms_square-0">
                      <div className="corners-0-0-0-0-0-0-0-0">
                        <div className="corners-_base_surface_shape_surface_master_shape-0">
                          <div className="corners-0-0-0-0-0-0-0-0-0-0">
                            <div className="corners-image-5">
                              <div className="corners-0-0-0-0-0-0-0-0-0-0-0-0">
                                <div className="corners-image-0" />
                              </div>
                            </div>
                          </div>
                          <div className="corners-0-0-0-0-0-0-0-0-0-1">
                            <div className="corners-0-0-0-0-0-0-0-0-0-1-0">
                              <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0">
                                <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0">
                                  <div className="corners-header-0">
                                    <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0">
                                      <div className="corners-image-2">
                                        <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0">
                                          <div className="corners-secondary_dark_gradient_color_-0000">
                                            <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0">
                                              <div className="corners-secondary_light_gradient_color_-0000">
                                                <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-0">
                                                  <div className="corners-secondary_light_gradient_color_-000">
                                                    <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-0-0-0">
                                                      <div className="corners-secondary_light_gradient_color_-00">
                                                        <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0">
                                                          <div className="corners-image-00">
                                                            <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0">
                                                              <div className="corners-secondary_dark_gradient_color_-000">
                                                                <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0">
                                                                  <div className="corners-secondary_light_gradient_color_-0">
                                                                    <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0">
                                                                      <div className="corners-secondary_dark_gradient_color_-00">
                                                                        <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0">
                                                                          <div className="corners-secondary_dark_gradient_color_-0" />
                                                                        </div>
                                                                      </div>
                                                                    </div>
                                                                  </div>
                                                                </div>
                                                              </div>
                                                            </div>
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                      <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-1">
                                        <div className="corners-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-1-0">
                                          <div className="corners-mask-0" />
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                  <div className="corners-headline_6">
                                    Headline 6
                                  </div>
                                  <div className="corners-body_2">Body 2</div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="corners-0-0-0-0-0-0-0-0-0-2">
                            <div className="corners-body_2-0">
                              Greyhound divisively hello coldly wonderfully
                              marginally far...
                            </div>
                          </div>
                          <div className="corners-0-0-0-0-0-0-0-0-0-3">
                            <div className="corners-buttons-0">
                              <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0">
                                <div className="corners-buttons_contained_enabled-0">
                                  <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-0-0">
                                    <div className="corners-button-0">
                                      <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-0-0-0-0">
                                        <div className="corners-rectangle-0">
                                          <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-0-0-0-0-0-0">
                                            <div className="corners-label-0">
                                              info
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-1">
                                  <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-1-0">
                                    <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-1-0-0">
                                      <div className="corners-b-1">
                                        Source component not found
                                      </div>
                                      <div className="corners-rectangle-00">
                                        <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-1-0-0-1-0">
                                          <div className="corners-label-00">
                                            info
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-2">
                                  <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-2-0">
                                    <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-2-0-0">
                                      <div className="corners-b-12">
                                        Source component not found
                                      </div>
                                      <div className="corners-rectangle-000">
                                        <div className="corners-0-0-0-0-0-0-0-0-0-3-0-0-2-0-0-1-0">
                                          <div className="corners-label-000">
                                            info
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="corners-cut_3" />
            <div className="corners-cut_4" />
            <div className="corners-cut_2" />
            <div className="corners-cut_1" />
          </div>
        </div>
      </div>
    );
  }
}
