// Generated by https://pagedraw.io/pages/11742
import React from "react";
import "./section2.css";

export default class Section2 extends React.Component {
  render() {
    return (
      <div className="section2-section2">
        <div className="section2-0">
          <div className="section2-rectangle-0">
            <div className="section2-0-0-0">
              <div className="section2-about-0">About</div>
            </div>
            <div className="section2-0-0-1">
              <div className="section2-hi_my_name_is_felipe_luj_n_im_a_geologist_working_really_hard_to_switch_carrer_into_software_development_and_hopefully_some_ai_in_the_future_im_a_self-taught_developer_bilingual_english_and_spanish_i_ve_mainly_focused_on_front-end_frameworks_such_as_angular_2">
                <div>
                  {
                    "Hi. My name is Felipe Luján. Im a Geologist working really hard to switch carrer into software development and hopefully some AI in the future. Im a self-taught developer, bilingual (English and Spanish). "
                  }
                </div>
                <div>
                  {
                    "I’ve mainly focused on Front-end frameworks such as Angular 2+ and React-Redux, but also worked quite a bit with Express servers on Node.js. Experienced with Linux environments."
                  }
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
