// Generated by https://pagedraw.io/pages/11741
import React from "react";
import "./subtitle.css";

export default class Subtitle extends React.Component {
  render() {
    return (
      <div className="subtitle-subtitle-4">
        <div className="subtitle-0">
          <div className="subtitle-web_developer-0">Web Developer</div>
        </div>
      </div>
    );
  }
}
