// Generated by https://pagedraw.io/pages/11740
import React from "react";
import "./title.css";

export default class Title extends React.Component {
  render() {
    return (
      <div className="title-title-1">
        <div className="title-0">
          <div className="title-felipe_lujan-0">Felipe Lujan</div>
        </div>
      </div>
    );
  }
}
